version: "3"
services:
  ssm:
    build:
      context: .
    environment:
      - SSMROLE=SSMRole
      - INSTANCENAME=ssm-container
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
